Add char count component
CriminalInjuriesCompensationAuthority/q-transformer pull request #52
Opened 2021-02-08 19:47 UTC by armoj

* Add new transformer for the `govukCharacterCount` component.
* Enforce a maxlength on `textarea` `input`, `characterCount` transformers

2021-02-10 12:20 UTC, BarryPiccinni approved these changes

2021-02-15 16:00 UTC, sinclairs requested changes

2021-02-15 16:07 UTC, armoj commented on test/q-transformer.test.js
> +                        dependencies: [
well spotted. Fixed

2021-02-15 18:04 UTC, sinclairs approved these changes

2021-02-15 20:52 UTC, merged